### ISSUE TITLE
Locale should be filled

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#18]
See review: https://github.com/graphhopper/directions-api-java-client/pull/20#pullrequestreview-778871

**Comment by boldtrn** [comment]
I checked for Nominatim and Opencage, but both do not return a locale, but both allow for querying a locale. But there seems to be no option to view the returned locale.

 We could just return the queried locale. Or we could setup a check if the given locale is a valid locale, and only return it if it is valid. Otherwise, return `en`. Not sure if there is another option?

**Comment by karussell** [comment]
Then I also see no other possibility.

**Comment by boldtrn** [comment]
This was fixed in https://github.com/boldtrn/graphhopper-geocoder-converter/commit/2b41c0f3505dce85072bc942f2a1abda034cec91
